### ISSUE TITLE
Give the opportunity to use another client to communicate with RabbitMQ

### ISSUE THREAD

**Issue by neeckeloo** [prolic/HumusAmqpModule#28]
You could use an adapter pattern for instance to give the opportunity to use another client to communicate with RabbitMQ. Some people can not or don't want use the PHP AMQP extension. In my case, we use `videlalvaro/php-amqplib` package for that.

https://github.com/videlalvaro/php-amqplib

**Comment by prolic** [comment]
This is resolved with the new package https://github.com/prolic/HumusAmqp. The module package will be update, as soon as the new lib is ready.
