### ISSUE TITLE
unable to get service locator from inside callback function

### ISSUE THREAD

**Issue by jackdpeterson** [prolic/HumusAmqpModule#30]
I'm currently implementing some functionality that relies on fetching a Domain service from inside the callback function. What is the appropriate way to get the service manager?

I've defined the invokable class inside of configuration as well as added the ServiceLocatorAwareInterface to my callback class. This is the typical approach that I would expect to work in order to be able to get access to the service manager; however, this does not appear to be the case.

```
Service "ExampleService" has been requested to plugin manager of type "HumusAmqpModule\PluginManager\Callback",
 but couldn't be retrieved.
A previous exception of type "Zend\ServiceManager\Exception\ServiceNotFoundException" has been raised in the process.
By the way, a service with the name "ExampleService" has been found in the parent service locator "Zend\ServiceManager\ServiceManager": did you forget to use $parentLocator = $serviceLocator->getServiceLocator() in your factory code?
```
is the exception that is thrown.

**Comment by prolic** [comment]
Hi. You really should not inject the service locator into the callback. You should inject your "ExampleService" in your callback.

**Comment by prolic** [comment]
A short example:

    class MyCallback
    {
        private $service;
    
        public function __construct($service)
        {
            $this->service = $service;
        }
    
        public function __invoke(AMQPEnvelope $msg, AMQPQueue $queue)
        {
            $this->service->doSometing($msg->getBody());
        }
    }
    
    class MyCallbackFactory implements \Zend\ServiceManager\FactoryInterface
    {
        public function createService(\Zend\ServiceManager\ServiceLocatorInterface $serviceLocator)
        {
            $sm = $serviceLocator->getServiceLocator();
            $service = $sm->get('ExampleService');
            return new MyCallback($service);
        }
    }
